// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDAcGBNlLob6eJcLA6ODxu10y07ly2vwD0',
    appId: '1:532562605363:web:07a6e16575d016b0f3fa46',
    messagingSenderId: '532562605363',
    projectId: 'homeservice-flutter-project',
    authDomain: 'homeservice-flutter-project.firebaseapp.com',
    storageBucket: 'homeservice-flutter-project.appspot.com',
    measurementId: 'G-HBTHMMJKFJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDPi1dKYTNECDbWM1ifgwwcBsyYv0DPQO4',
    appId: '1:532562605363:android:1acf196bff8ddab1f3fa46',
    messagingSenderId: '532562605363',
    projectId: 'homeservice-flutter-project',
    storageBucket: 'homeservice-flutter-project.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBftivcm9XGdyRfppF-VeEcUOmM9GtdNEI',
    appId: '1:532562605363:ios:125ce696a6f88581f3fa46',
    messagingSenderId: '532562605363',
    projectId: 'homeservice-flutter-project',
    storageBucket: 'homeservice-flutter-project.appspot.com',
    iosBundleId: 'com.example.homeservice',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBftivcm9XGdyRfppF-VeEcUOmM9GtdNEI',
    appId: '1:532562605363:ios:41852d86cb576018f3fa46',
    messagingSenderId: '532562605363',
    projectId: 'homeservice-flutter-project',
    storageBucket: 'homeservice-flutter-project.appspot.com',
    iosBundleId: 'com.example.homeservice.RunnerTests',
  );
}
